### ISSUE TITLE
Call Stack Logger – Function instrumentation as a way to trace program’s flow of execution - blogersii

### ISSUE THREAD

**Issue by th-sabik** [rokath/trice#248]
https://sii.pl/blog/call-stack-logger-function-instrumentation-as-a-way-to-trace-programs-flow-of-execution/

**Comment by rokath** [comment]
This could be an application example for gcc compiled projects.

**Comment by rokath** [comment]
Now part of similar projects list

**Comment by TomaszAugustyn** [comment]
Hello @rokath / Thomas

I checked your project and I must say it looks incredible. Although I'm not working with C, I can see how much hard work you have put into this project. It's very sophisticated, great work!

I have also noticed that you put my project (Call Stack Logger) into "Similar Projects" section and I'm honored and grateful for that. I noticed that Sii has recently changed their blog appearance and the code snippets look very bad there. That's why I migrated the article to Dev.to and Hashnode. Maybe you could update the link to the article? 
https://dev.to/taugustyn/call-stack-logger-function-instrumentation-as-a-way-to-trace-programs-flow-of-execution-419a

Best regards,
Tomasz.

**Comment by rokath** [comment]
Thanks for the update, Tomaz, and your * :-)

Thomas


Am Mi., 17. Aug. 2022 um 01:17 Uhr schrieb TomaszAugustyn <
***@***.***>:
