### ISSUE TITLE
assert() implementation using trice macros.

### ISSUE THREAD

**Issue by mmurty** [rokath/trice#434]
I am trying to implement assert() using trice macros but I am unable to implement it as expected.
If you have a solution in mind please suggest.

```
#define MY_ASSERT(expr)        \
     if (!(expr)) {            \
      TRICE_S( ID(1613), "err: Assert triggered %s ", __FILE__);\
      trice( iD(3634), "%u \n", __LINE__);                      \
    }                                                           \
    APP_ASSERT_DUMP_LOGS()
```
Ideally if it is possible to generate the strings at compile time it would be a great feature.

**Comment by rokath** [comment]
When you write:
```C
#define MY_ASSERT( expr ) if(!expr){ trice( "fatal:Assert triggered\n"); }
```
after `trice insert` it changes into like this:
```C
#define MY_ASSERT( expr ) if(!expr){ trice( iD(1234), "fatal:Assert triggered\n"); }
```
This is what you compile.
 The problem here is, that the id 1234 is bound to the file and line number, where you defined the macro. Therefore you do not get the correct location information.
I would go with `if(!expr){ trice( "fatal:Assert triggered\n"); }` instead of using an assert macro. After `trice insert` all these lines get different IDs and you will have correct location informantion for nothing.
In an old trice version I did assign the __FILE__ names to IDs but I forgot the details. Maybe it makes sense to dig that out again, but I do not know...
An other option could be to write in **triceConfig.h** s.th. like `#define TRICE_ASSERT_MESSAGE "fatal:Assert triggered\n"` and to extend the `trice insert` command to replace all `TRICE_ASSERT( expr )` with `if(!expr){ trice( "fatal:Assert triggered\n"); }` before inserting the IDs and to change that back with `trice clean`. That would be possible but I am not convinced if that is a good idea.

**Comment by mmurty** [comment]
I see that the last option should be ideal approach i.e. extending `trice insert`. If we simply replace all `TRICE_ASSERT( expr )` expressions with the `if` block I think the code will get too much cluttered. Also if you notice in the above comment, I also have `APP_ASSERT_DUMP_LOGS()` which stops the RTOS, keeps global interrupts enabled and keeps on calling UartDumpBuffer() continuously. We may require different implementation of `DUMP_LOGS()` based on the communication transport used.
Going forward, the `DUMP_LOGS()` function could also be extended to capture stack trace which can then be analyzed at the PC side.

To start with I am thinking of something similar to `trice()` macros.
Where `TRICE_ASSERT( expr )` should be replaced with `TRICE_ASSERT(1234, expr)` on insert and 1234 should disappear on clean. 

What are your thoughts on possibility of this?

**Comment by rokath** [comment]
This is a nice idea, mmurty!

**Comment by mmurty** [comment]
Cool. I will start looking into the Go code. In the meantime are there any contributing guidelines to this project? It will serve as a starting point to setup the development environment and introduce me to the tools used. I am a Windows user. 
By the way, I did not work on Go before, so I will have to start from learning the language. 
If there is a specific way you want me to proceed or you want me to look at a specific portion of code to gain better understanding please let me know that.

**Comment by rokath** [comment]
About Go you can find [here](https://github.com/rokath) a few resources. What is weak in the trice tool is the parsing - that could be done better. The `trice update` command is obsolete and exists now only for compatibility and `trice insert` & `trice clean` are usable but not perfect - they scans all the comments as well. Maybe we find a solution by mainly extending the C-source and just a bit the trice parser. Example:
```C
void triceAssert( int id, bool flag ){
    if( !flag ){
         TRICE_ASSERT( id );
    }
}
```

**Comment by rokath** [comment]
In the development branch there is now an experimental implementation. Usage:
```C
    triceAssert( "FATAL:Oh, no 1st test!\n", 0 );    // no time stamp
    TRiceAssert( "FATAL:Oh, no 2nd test!\n", 1 ); // 32-bit time stamp
    TriceAssert( "FATAL:Oh, no 3rd test!\n", 0 );  //16-bit time stamp
```
To try it out: `git pull && git switch development && git pull && go install ./...`

Would that meet your needs sufficiently?

Probably it would be nicer to have the flag in front of the message, which could be also "" because of the location information, but this way I had not to change too much.

**Comment by rokath** [comment]
BTW: You asked: "are there any contributing guidelines to this project?" --> https://github.com/rokath/trice/blob/master/CONTRIBUTING.md

**Comment by mmurty** [comment]
Thanks for the implementation. I will try to check it (and improve if possible) and let you know.

**Comment by rokath** [comment]
Hi @mmurty, any news concerning this issue? If Not, I would propose to merge my tryout implementation into the main branch. Or let me know, if you need more time.

**Comment by mmurty** [comment]
Please go ahead with your implementation. Due to other commitments I did not yet have enough progress in this direction. In case I have any progress I will raise a pull request.

**Comment by rokath** [comment]
```c
        triceAssertTrue( "x", flag );
	TriceAssertTrue( "x", flag );
	TRiceAssertTrue( "x", flag );
	triceAssertFalse( "x", flag );
	TriceAssertFalse( "x", flag );
	TRiceAssertFalse( "x", flag );
```
are now usable in the main branch.
