### ISSUE TITLE
PR : Labeler / label (pull_request) Failing

### ISSUE THREAD

**Issue by Sazerac4** [rokath/trice#496]
When i do a PR, "labeler /label" fail.
I'm not familiar with github labels. Anyone have an idea?

**Comment by rokath** [comment]
Yesterday I saw a _draft_ pull request from you and there was a button "approve" or similar which I pressed just to see. Then the button disappeared and totay I do not see your PR either. I did nothing else. If you plan to work more on Trice, I could enable you as a co-worker so that you can push directly.

**Comment by Sazerac4** [comment]
I have draft/undrafr the PR ? Do you see it again  ( #495 )
